version: "3.9"

services:

  nginx:
    image: proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - robotreviewer_network
      - trialstreamer-demo_network
      - trialstreamer-api_network
    volumes:
      - letsencrypt:/etc/letsencrypt
      - wwwroot:/var/www/certbot

  certbot:
    image: certbot
    build: ./certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - wwwroot:/var/www/certbot
    command: print-version

volumes:
  letsencrypt:
  wwwroot:

networks:
  robotreviewer_network:
    external: true
    name: robotreviewer_default
  trialstreamer-demo_network:
    external: true
    name: trialstreamer-demo_default
  trialstreamer-api_network:
    external: true
    name: trialstreamer_default
